# Generated by Django 2.2.3 on 2019-11-11 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('size', models.IntegerField(choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXXL')], help_text='int，Size大小', verbose_name='Size')),
                ('quantity', models.IntegerField(help_text='int，库存量', verbose_name='Quantity')),
            ],
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='active_porduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='store.ActivePorduct', verbose_name='ActivePorduct'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='productsize',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='store.ProductColor', verbose_name='ProductColor'),
        ),
    ]
