# Generated by Django 2.2.3 on 2019-11-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191111_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='size',
            new_name='sizes',
        ),
    ]
