# Generated by Django 2.2.3 on 2019-11-11 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20191111_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='sizes',
        ),
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.IntegerField(choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXXL')], default=0, help_text='int，Size大小', verbose_name='Sizes'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.ProductColor', verbose_name='ProductColor'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.IntegerField(default=0, help_text='int，库存量', verbose_name='Quantity'),
        ),
    ]
