# Generated by Django 2.2.3 on 2019-11-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20191111_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='etag',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='request_id',
        ),
        migrations.AlterField(
            model_name='image',
            name='file_name',
            field=models.CharField(help_text='上传图片路径及文件名', max_length=50, verbose_name='FileName'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='active_porduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='store.ActivePorduct', verbose_name='ActivePorduct'),
        ),
    ]
