# Generated by Django 2.2.3 on 2019-11-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20191111_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_name',
        ),
        migrations.AddField(
            model_name='image',
            name='file_url',
            field=models.CharField(default='', help_text='上传图片路径及文件名', max_length=50, verbose_name='FileUrl'),
            preserve_default=False,
        ),
    ]
