# Generated by Django 2.2.3 on 2019-11-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20191111_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeporduct',
            name='care',
            field=models.TextField(default='', help_text='text，养护', verbose_name='Care'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activeporduct',
            name='feature',
            field=models.TextField(default='', help_text='text，特征', verbose_name='Features'),
            preserve_default=False,
        ),
    ]
