# Generated by Django 2.2.3 on 2019-11-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20191112_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeporduct',
            name='feature',
            field=models.CharField(help_text='text，特征', max_length=500, verbose_name='Features'),
        ),
    ]
