# Generated by Django 2.2.3 on 2019-11-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20191112_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeporduct',
            name='feature',
            field=models.TextField(help_text='text，特征', verbose_name='Features'),
        ),
    ]
