# Generated by Django 2.2.3 on 2019-11-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20191112_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeporduct',
            name='height',
            field=models.IntegerField(choices=[(0, 'NO-SHOW'), (1, 'TAB'), (2, 'ANKLE'), (3, 'CREW'), (4, 'OVER THE CALF')], help_text='int，高度', verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='activeporduct',
            name='thickness',
            field=models.IntegerField(choices=[(0, 'THIN'), (1, 'MEDIUM'), (2, 'THICK')], help_text='int，厚度', verbose_name='Thickness'),
        ),
    ]
