# Generated by Django 2.2.3 on 2019-11-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20191113_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='etag',
            field=models.CharField(default='', max_length=250, verbose_name='Etag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='request_id',
            field=models.CharField(default='', max_length=250, verbose_name='RequestId'),
            preserve_default=False,
        ),
    ]
