# Generated by Django 2.2.3 on 2019-11-13 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20191113_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oreder',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('address', models.TextField(help_text='收货信息', verbose_name='Address')),
                ('total_price', models.FloatField(help_text='总价', verbose_name='TotalPrice')),
                ('state', models.IntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待确认'), (3, '待退货'), (4, '其他'), (5, '已完成')], default=0, help_text='int，订单状态', verbose_name='State')),
                ('product', models.ManyToManyField(help_text='[int]，外键-ProductSize', to='store.ProductSize', verbose_name='Product')),
                ('user', models.ForeignKey(help_text='int，外键-User', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
