# Generated by Django 2.2.3 on 2019-11-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_oreder'),
    ]

    operations = [
        migrations.AddField(
            model_name='oreder',
            name='count',
            field=models.IntegerField(default=1, help_text='购买数量', verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='oreder',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='CreateTime'),
        ),
        migrations.AddField(
            model_name='oreder',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='EditTime'),
        ),
        migrations.AddField(
            model_name='oreder',
            name='extra',
            field=models.TextField(default='', help_text='备注', verbose_name='Extra'),
            preserve_default=False,
        ),
    ]
