# Generated by Django 2.2.3 on 2019-11-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20191113_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oreder',
        ),
    ]
