# Generated by Django 2.2.3 on 2019-11-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_delete_oreder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeporduct',
            name='name',
            field=models.CharField(help_text='string，产品名称', max_length=128, verbose_name='Name'),
        ),
    ]
