# Generated by Django 2.2.3 on 2019-11-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20191118_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeporduct',
            name='active_describe',
            field=models.TextField(default='', help_text='string，活动简介', verbose_name='ActiveDescribe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activeporduct',
            name='active_name',
            field=models.CharField(default='', help_text='string，活动名称', max_length=128, verbose_name='ActiveName'),
            preserve_default=False,
        ),
    ]
