# Generated by Django 2.2.3 on 2019-11-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20191128_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeporduct',
            name='active_images',
            field=models.ManyToManyField(help_text='[int]，外键-Image，活动图片', to='store.Image', verbose_name='Active_Image'),
        ),
    ]
