# Generated by Django 2.2.3 on 2019-11-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_delete_oreder'),
        ('wechat_store_miniprogram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatOreder',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1, help_text='购买数量', verbose_name='Count')),
                ('address', models.TextField(help_text='收货信息', verbose_name='Address')),
                ('total_price', models.FloatField(help_text='总价', verbose_name='TotalPrice')),
                ('extra', models.TextField(help_text='备注', verbose_name='Extra')),
                ('state', models.IntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待确认'), (3, '待退货'), (4, '其他'), (5, '已完成')], default=0, help_text='int，订单状态', verbose_name='State')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='CreateTime')),
                ('edit_time', models.DateTimeField(auto_now=True, null=True, verbose_name='EditTime')),
                ('product', models.ManyToManyField(help_text='[int]，外键-ProductSize', to='store.ProductSize', verbose_name='Product')),
                ('user', models.ForeignKey(help_text='int，外键-WeUser', on_delete=django.db.models.deletion.PROTECT, to='wechat_store_miniprogram.WeUser', verbose_name='WeUser')),
            ],
        ),
    ]
