# Generated by Django 2.2.3 on 2019-11-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0002_wechatoreder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wechatoreder',
            old_name='user',
            new_name='we_user',
        ),
    ]
