# Generated by Django 2.2.3 on 2019-11-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0003_auto_20191113_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('is_hide', models.BooleanField(verbose_name='Destroy')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wechat_store_miniprogram.WeChatOreder', verbose_name='Order')),
            ],
        ),
    ]
