# Generated by Django 2.2.3 on 2019-11-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_delete_oreder'),
        ('wechat_store_miniprogram', '0004_userorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatoreder',
            name='product',
        ),
        migrations.AddField(
            model_name='wechatoreder',
            name='out_trade_no',
            field=models.CharField(default='', help_text='string，商户订单号', max_length=50, verbose_name='OutTradeNo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wechatoreder',
            name='state',
            field=models.IntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待确认'), (3, '退货中'), (4, '其他'), (5, '已完成')], default=0, help_text='int，订单状态', verbose_name='State'),
        ),
        migrations.CreateModel(
            name='OrderPackge',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('count', models.IntegerField(help_text='int，数量', verbose_name='Count')),
                ('is_refund', models.BooleanField(help_text='bool，是否需要退货', verbose_name='IsRefund')),
                ('refund_count', models.IntegerField(default=0, help_text='int，退货数量', verbose_name='RefundCount')),
                ('product', models.OneToOneField(help_text='int，外键-ProductSize', on_delete=django.db.models.deletion.CASCADE, to='store.ProductSize', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderExpress',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('code', models.TextField(help_text='text，快递单号', verbose_name='ExpressCode')),
                ('order', models.ForeignKey(blank=True, help_text='int，外键-WeChatOreder', null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat_store_miniprogram.WeChatOreder', verbose_name='WeChatOreder')),
            ],
        ),
        migrations.AddField(
            model_name='wechatoreder',
            name='product_packge',
            field=models.ManyToManyField(help_text='[int]，外键-models.Model', to='wechat_store_miniprogram.OrderPackge', verbose_name='Product'),
        ),
    ]
