# Generated by Django 2.2.3 on 2019-11-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0005_auto_20191114_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPackge',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('refund_count', models.IntegerField(default=0, help_text='int，退货数量', verbose_name='RefundCount')),
                ('order_packge', models.ForeignKey(help_text='int，外键-OrderPackge', on_delete=django.db.models.deletion.CASCADE, to='wechat_store_miniprogram.OrderPackge', verbose_name='OrderPackge')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('extra', models.TextField(help_text='备注', verbose_name='Extra')),
                ('price', models.FloatField(help_text='待退款金额', verbose_name='Price')),
                ('state', models.IntegerField(choices=[(0, '待退货'), (1, '待确认'), (2, '其他情况'), (3, '已完成')], default=0, help_text='int，状态', verbose_name='State')),
                ('express_code', models.TextField(blank=True, help_text='text，快递单号', null=True, verbose_name='ExpressCode')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='CreateTime')),
                ('edit_time', models.DateTimeField(auto_now=True, null=True, verbose_name='EditTime')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wechat_store_miniprogram.WeChatOreder', verbose_name='WeChatOreder')),
                ('refund_packge', models.ManyToManyField(help_text='[int]，外键-RefundPackge', to='wechat_store_miniprogram.RefundPackge', verbose_name='RefundPackge')),
            ],
        ),
    ]
