# Generated by Django 2.2.3 on 2019-11-15 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0007_auto_20191114_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundpackge',
            name='order_packge',
            field=models.OneToOneField(help_text='int，外键-OrderPackge', on_delete=django.db.models.deletion.CASCADE, to='wechat_store_miniprogram.OrderPackge', verbose_name='OrderPackge'),
        ),
    ]
