# Generated by Django 2.2.3 on 2019-11-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0008_auto_20191115_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatoreder',
            name='count',
        ),
    ]
