# Generated by Django 2.2.3 on 2019-11-18 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0009_remove_wechatoreder_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackge',
            name='product',
            field=models.ForeignKey(help_text='int，外键-ProductSize', on_delete=django.db.models.deletion.CASCADE, to='store.ProductSize', verbose_name='Product'),
        ),
    ]
