# Generated by Django 2.2.3 on 2019-11-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0010_auto_20191118_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatoreder',
            name='extra',
            field=models.TextField(blank=True, help_text='备注', null=True, verbose_name='Extra'),
        ),
    ]
