# Generated by Django 2.2.3 on 2019-11-21 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0011_auto_20191118_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderexpress',
            name='order',
            field=models.ForeignKey(blank=True, help_text='int，外键-WeChatOreder', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_express', to='wechat_store_miniprogram.WeChatOreder', verbose_name='WeChatOreder'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='extra',
            field=models.TextField(help_text='退货理由', verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='wechat_store_miniprogram.WeChatOreder', verbose_name='WeChatOreder'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='state',
            field=models.IntegerField(choices=[(0, '待通过'), (1, '待退货'), (2, '待确认'), (3, '已完成')], default=0, help_text='int，状态', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='is_hide',
            field=models.BooleanField(default=False, verbose_name='Destroy'),
        ),
    ]
