# Generated by Django 2.2.3 on 2019-11-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0012_auto_20191121_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='out_refund_no',
            field=models.CharField(default='', help_text='string，退款单号', max_length=50, verbose_name='OutRefundNo'),
            preserve_default=False,
        ),
    ]
