# Generated by Django 2.2.3 on 2019-11-25 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0015_auto_20191125_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackge',
            name='order',
            field=models.ForeignKey(help_text='int，外键-WeChatOreder', on_delete=django.db.models.deletion.CASCADE, related_name='order_packge', to='wechat_store_miniprogram.WeChatOreder', verbose_name='WeChatOreder'),
        ),
    ]
