# Generated by Django 2.2.3 on 2019-11-25 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0017_auto_20191125_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatoreder',
            name='product_packge',
        ),
        migrations.AddField(
            model_name='orderpackge',
            name='order',
            field=models.ForeignKey(default='', help_text='int，外键-ProductSize', on_delete=django.db.models.deletion.CASCADE, related_name='order_packge', to='wechat_store_miniprogram.WeChatOreder', verbose_name='WeChatOreder'),
            preserve_default=False,
        ),
    ]
