# Generated by Django 2.2.3 on 2019-11-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0020_auto_20191125_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='re_extra',
            field=models.TextField(blank=True, help_text='答复信息', null=True, verbose_name='ReExtra'),
        ),
    ]
