# Generated by Django 2.2.3 on 2019-11-26 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0021_auto_20191125_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundpackge',
            old_name='order_packge',
            new_name='order_package',
        ),
        migrations.AlterField(
            model_name='orderpackge',
            name='order',
            field=models.ForeignKey(help_text='int，外键-WeChatOreder', on_delete=django.db.models.deletion.CASCADE, related_name='order_package', to='wechat_store_miniprogram.WeChatOreder', verbose_name='WeChatOreder'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='state',
            field=models.IntegerField(choices=[(0, '待通过'), (1, '待退货'), (2, '待确认'), (3, '已完成'), (4, '未通过'), (5, '协商中')], default=0, help_text='int，状态', verbose_name='State'),
        ),
    ]
