# Generated by Django 2.2.3 on 2019-11-26 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0022_auto_20191126_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundpackge',
            name='refund',
            field=models.ForeignKey(help_text='int，外键-Refund', on_delete=django.db.models.deletion.CASCADE, related_name='refund_package', to='wechat_store_miniprogram.Refund', verbose_name='Refund'),
        ),
    ]
