# Generated by Django 2.2.3 on 2019-12-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0023_auto_20191126_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(blank=True, max_length=128, null=True, verbose_name='APPID')),
                ('expires_in', models.DateTimeField(default='2019-12-10 14:01:25', verbose_name='expires_in')),
                ('token', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='token')),
            ],
            options={
                'verbose_name': '小程序access_token信息',
                'verbose_name_plural': '小程序access_token信息',
            },
        ),
        migrations.AlterField(
            model_name='refund',
            name='state',
            field=models.IntegerField(choices=[(0, '待通过'), (1, '待退货'), (2, '待确认'), (3, '已完成'), (4, '未通过'), (5, '未发货退款待通过'), (6, '未发货退款已完成')], default=0, help_text='int，状态', verbose_name='State'),
        ),
    ]
