# Generated by Django 2.2.3 on 2019-12-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_store_miniprogram', '0026_auto_20191218_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptoken',
            name='expires_in',
            field=models.DateTimeField(default='2019-12-23 11:55:27', verbose_name='expires_in'),
        ),
    ]
